Add the ability to pass args to MavenPublisher
bazelbuild/rules_jvm_external pull request #937
Opened 2023-07-25 19:36 UTC by loganasherjones

This is an attempt to address #936

2023-07-25 19:41 UTC, loganasherjones commented
Signed CLA

2023-08-03 00:07 UTC, loganasherjones commented
Do I need to do something additional to get this reviewed? I don't anticipate getting it accepted immediately, but I was hoping to start a conversation around this PR. 

Is the CLA check causing people not to review it? I believe I've signed it, just wanted to make sure I'm moving the ball forward.

2023-08-17 13:58 UTC, shs96c commented
Sorry for the delay getting back to you. I was on vacation for a while. Reviewing now!

2023-08-17 14:02 UTC, shs96c requested changes

2023-08-17 14:02 UTC, shs96c commented on private/rules/maven_publish.bzl
> +{uploader} $@ '{maven_repo}' '{gpg_sign}' '{user}' '{password}' '{coordinates}' '{pom}' '{artifact_jar}' '{source_jar}' '{javadoc}'
The `MavenPublisher` is very sensitive to the order in which arguments appear, and the parsing of the command line is very basic. Could you please append additional arguments to the end of the command line? Alternatively, could you please update the `MavenPublisher` to skip arguments beginning with a dash? I think that second suggestion also allows you to do what you need.

2023-08-17 23:19 UTC, thirtyseven commented on private/rules/maven_publish.bzl
> +{uploader} $@ '{maven_repo}' '{gpg_sign}' '{user}' '{password}' '{coordinates}' '{pom}' '{artifact_jar}' '{source_jar}' '{javadoc}'
@shs96c: @loganasherjones is trying to use this to pass arguments to the Bazel wrapper script, which currently uses [this logic](https://github.com/bazelbuild/bazel/blob/48f081f6f18277d4bbbb5a1740f9c59cecdf88fc/src/main/java/com/google/devtools/build/lib/bazel/rules/java/java_stub_template.txt#L113) to distinguish between its own flags and flags passed to the underlying java process:
```bash
# Parse arguments sequentially until the first unrecognized arg is encountered.
# Scan the remaining args for --wrapper_script_flag=X options and process them.
ARGS=()
for ARG in "$@"; do
  if [[ "$ARG" == --wrapper_script_flag=* ]]; then
    process_wrapper_argument "${ARG#--wrapper_script_flag=}" \
      || die "invalid wrapper argument '%s'" "$ARG"
  elif [[ "${#ARGS}" -gt 0 ]] || ! process_wrapper_argument "$ARG"; then
    ARGS+=( "$ARG" )
  fi
done
```

Thus, any valid wrapper script flags will not be passed to the actual publisher binary. It could be worth implementing your second suggestion as an extra safeguard, but if going with the first option, wrapper script flags will need to be prefixed with `--wrapper_script_flag=`.

2023-08-18 01:58 UTC, loganasherjones commented on private/rules/maven_publish.bzl
> +{uploader} $@ '{maven_repo}' '{gpg_sign}' '{user}' '{password}' '{coordinates}' '{pom}' '{artifact_jar}' '{source_jar}' '{javadoc}'
Welcome back @shs96c hope you had a wonderful vacation!

@thirtyseven is correct, I mostly just hacked something together as a POC to prove that I could get to the wrapper script and get me unblocked.  I'm happy to add the args at the end, and use the `--wrapper_script_flag`.  I also wouldn't mind updating `MavenPublisher`. Whatever you all think is best.

If you do want me to update `MavenPublisher`, is it really just a matter of ignoring args with `-` in their name? Would you rather me expand `MavenPublisher` to have more robust arg parsing all around?

2023-08-20 00:49 UTC, loganasherjones commented on private/rules/maven_publish.bzl
> +{uploader} $@ '{maven_repo}' '{gpg_sign}' '{user}' '{password}' '{coordinates}' '{pom}' '{artifact_jar}' '{source_jar}' '{javadoc}'
Another option I suppose is to take the part of the function from the wrapper script and copy it into the template.

2023-08-20 00:53 UTC, loganasherjones commented on private/rules/maven_publish.bzl
> +{uploader} $@ '{maven_repo}' '{gpg_sign}' '{user}' '{password}' '{coordinates}' '{pom}' '{artifact_jar}' '{source_jar}' '{javadoc}'
One more option that I was thinking of was updating `MavenPublisher` to work off of environment variables that get set in the script instead. All of these seem do-able, just let me know which one you want, and I'll get a PR with that functionality up.

2024-01-27 23:59 UTC, loganasherjones commented on private/rules/maven_publish.bzl
> +{uploader} $@ '{maven_repo}' '{gpg_sign}' '{user}' '{password}' '{coordinates}' '{pom}' '{artifact_jar}' '{source_jar}' '{javadoc}'
Ok @shs96c thanks for the review. I've moved the args to the end to prevent any unexpected behavior. Please let me know if you need any additional changes!

2024-01-29 10:40 UTC, shs96c approved these changes
LGTM. Thank you for your patience and understanding!

2024-01-29 10:40 UTC, merged